#line 2 "dfgscanner.c"

#line 4 "dfgscanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE dfg_restart(dfg_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int dfg_leng;

extern FILE *dfg_in, *dfg_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up dfg_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up dfg_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via dfg_restart()), so that the user can continue scanning by
	 * just pointing dfg_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when dfg_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int dfg_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow dfg_wrap()'s to do buffer switches
 * instead of setting up a fresh dfg_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void dfg_restart (FILE *input_file  );
void dfg__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE dfg__create_buffer (FILE *file,int size  );
void dfg__delete_buffer (YY_BUFFER_STATE b  );
void dfg__flush_buffer (YY_BUFFER_STATE b  );
void dfg_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void dfg_pop_buffer_state (void );

static void dfg_ensure_buffer_stack (void );
static void dfg__load_buffer_state (void );
static void dfg__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER dfg__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE dfg__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE dfg__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE dfg__scan_bytes (yyconst char *bytes,int len  );

void *dfg_alloc (yy_size_t  );
void *dfg_realloc (void *,yy_size_t  );
void dfg_free (void *  );

#define yy_new_buffer dfg__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        dfg_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dfg__create_buffer(dfg_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        dfg_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dfg__create_buffer(dfg_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define dfg_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *dfg_in = (FILE *) 0, *dfg_out = (FILE *) 0;

typedef int yy_state_type;

extern int dfg_lineno;

int dfg_lineno = 1;

extern char *dfg_text;
#define yytext_ptr dfg_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up dfg_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	dfg_leng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[520] =
    {   0,
        0,    0,    0,    0,   92,   90,   87,   88,   79,   89,
       90,    3,   89,   85,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   90,   90,   82,   83,
       87,   79,   81,   78,    2,   85,   86,   22,   86,   86,
       86,   86,   86,   86,   86,    8,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   35,   86,   86,   86,   86,   86,
       86,   52,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   80,    1,   82,   83,

       83,   84,    9,    4,   86,   86,   86,   86,   11,   86,
       86,   86,   86,   17,   18,   19,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       50,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   71,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   12,   86,   86,   14,
       15,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   49,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   66,
       86,   69,   86,   72,   86,   74,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       25,   26,   86,   28,   86,   86,   86,   86,   86,   86,
       86,   86,   48,   86,   86,   86,   86,   58,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   67,   86,   86,
       86,   86,   86,   86,    5,    6,   86,   10,   86,   86,
       86,   20,   86,   86,   86,   27,   29,   86,   31,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   68,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       30,   86,   86,   86,   36,   37,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       70,   86,   75,   86,   77,   86,   86,   86,   86,   21,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       57,   86,   86,   86,   86,   86,   62,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   32,   33,   86,
       86,   86,   86,   86,   86,   86,   86,   51,   54,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   34,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   55,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       13,   16,   23,   24,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   56,   59,   86,   60,   86,
       61,   86,   86,   73,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   53,   86,   86,
       86,   86,    7,   86,   86,   86,   86,   86,   86,   43,
       86,   86,   86,   47,   86,   86,   65,   76,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   63,   38,
       86,   86,   86,   86,   86,   86,   46,   86,   86,   86,
       41,   86,   44,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       39,   40,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   42,   45,   86,   64,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    4,    1,    1,    5,
        5,    6,    7,    5,    8,    5,    1,    9,   10,    9,
        9,    9,    9,    9,    9,    9,    9,    5,    1,    1,
        1,   11,    1,    1,   12,   12,   13,   14,   15,   16,
       12,   12,   12,   12,   12,   17,   18,   12,   12,   19,
       12,   20,   12,   12,   12,   12,   12,   12,   12,   12,
        5,    1,    5,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   12,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[525] =
    {   0,
        0,    0,  765,  764,  769,  772,  766,  772,    0,  772,
      718,  772,   40,   43,    0,  749,  747,   21,   29,   24,
       42,   35,   40,  738,  717,   33,   51,   49,   47,  723,
      719,   66,   67,   35,  725,  733,  752,  709,    0,   77,
      754,    0,  772,  772,  772,   81,    0,    0,  738,  721,
      728,  711,  721,  722,  704,    0,  726,  720,   60,  705,
      705,   74,  717,  709,  709,  716,  698,  709,  705,  698,
      710,  700,  699,  696,    0,  695,  691,  702,  695,  687,
      701,    0,   71,  704,  690,  691,  690,  681,  680,   65,
       79,   77,  680,   76,   74,  680,  772,  772,    0,  104,

      106,  772,    0,    0,  689,  681,  686,  673,    0,  677,
       89,  687,  688,    0,    0,    0,   94,  690,   93,  670,
      669,   97,  682,  683,  680,  669,  671,  662,  672,  675,
        0,  661,  674,  661,  662,   96,  675,  669,  664,  672,
      666,  650,  649,  652,  648,    0,  646,  651,  659,  649,
      661,  642,  645,  646,  644,  638,    0,  651,  650,    0,
        0,  636,  644,  647,   85,  639,  628,  629,  643,  635,
      625,  633,  624,  625,  622,  632,  640,  636,    0,  637,
      628,  636,  615,  629,  628,  626,  631,  611,  114,  610,
      607,    0,  612,    0,  607,    0,  610,  604,  614,  604,

      602,  620,  614,  602,  614,  607,  601,  595,  607,  594,
        0,    0,  592,    0,  598,  597,  583,  598,  605,  597,
      599,  588,    0,  582,  598,  594,  590,    0,  579,  582,
      590,  589,  582,  578,  580,  573,  585,    0,  570,  570,
      575,  563,  576,  569,    0,    0,  567,    0,  562,  561,
      564,    0,  559,  578,  562,    0,    0,  575,    0,  560,
      554,  568,  100,  566,  556,  569,  554,  562,  547,  548,
      550,  555,  562,  549,  560,  555,  547,    0,  538,  541,
      542,  536,  540,  535,  552,  530,  530,  531,  536,  545,
        0,  532,  540,  525,    0,    0,  543,  524,  521,  522,

      530,  520,  524,  518,  534,  513,  535,  525,  528,  525,
        0,  528,    0,  522,    0,  512,  520,  507,  515,    0,
      514,  510,  502,  516,  510,  119,  499,  512,  503,  510,
        0,  493,  500,  510,  492,  492,    0,  504,  505,  498,
      497,  503,  489,  498,  487,  482,  495,    0,    0,  480,
      486,  492,  481,  490,  476,  111,  488,    0,  473,  470,
      472,  477,  467,  475,  481,  480,  480,  463,  464,  480,
      468,  461,  459,  463,  456,  462,    0,  473,  105,  455,
      458,  456,  450,  464,  455,  449,    0,  454,  446,  463,
      451,  457,  466,  456,  454,  449,  438,  454,  450,  441,

        0,    0,    0,    0,  432,  440,  448,  437,  444,  433,
      427,  443,  443,  431,  442,    0,    0,  441,    0,  426,
        0,  426,  424,    0,  426,  424,  415,  416,  433,  415,
      411,  413,  424,  420,  419,  412,  407,    0,  407,  421,
      409,  417,    0,  409,  415,  401,  409,  405,  415,    0,
      401,  413,  401,    0,  399,  406,    0,    0,  409,  390,
      407,  391,  405,  393,  397,  391,  383,  380,    0,    0,
      380,  379,  393,  397,  377,  395,    0,  382,  384,  383,
        0,  372,    0,  384,  388,  373,  372,  381,  370,  385,
      369,  368,  361,  362,  374,  359,  358,  356,  362,  362,

        0,    0,  272,  219,  190,  123,  119,  109,  121,  120,
      109,   98,  110,   98,    0,    0,   95,    0,  772,  160,
      209,  250,  296,  345
    } ;

static yyconst flex_int16_t yy_def[525] =
    {   0,
      519,    1,  520,  520,  519,  519,  519,  519,  521,  519,
      519,  519,  519,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  519,  519,  523,  524,
      519,  521,  519,  519,  519,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  519,  519,  523,  524,

      524,  519,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,    0,  519,
      519,  519,  519,  519
    } ;

static yyconst flex_int16_t yy_nxt[822] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   14,
        6,   15,   15,   16,   17,   15,   15,   15,   15,   15,
       15,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       15,   15,   27,   15,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   15,   15,   15,   37,   38,    6,   44,
       45,   46,   46,   50,   54,   51,   57,   75,   58,   59,
       93,   69,   52,   60,   55,   53,   76,   61,   65,   66,
       79,   62,   67,   94,   56,   70,   63,   64,   71,   68,
       77,   72,  101,   81,   80,   82,   78,   85,   88,   46,
       46,   86,   89,  110,  111,  114,  133,  148,  141,  145,

      143,   87,   90,  142,  144,  150,  134,   91,   92,  519,
      146,  101,  158,  151,  166,  163,  115,  149,  170,  159,
      209,  210,  167,  184,  295,  102,  233,  234,  406,  518,
      171,  160,  164,  517,  185,  516,  383,  515,  514,  296,
      235,  513,  351,  352,  407,  353,  354,  384,  512,  511,
      236,  510,  519,  237,  102,  355,  385,  509,  356,  357,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   42,
       42,  508,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   47,   47,
      507,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   99,   99,   99,   99,

       99,  506,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  505,  504,  503,  502,  501,  500,

      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      438,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  417,  438,  437,  436,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  408,  405,  404,  403,  402,  401,  400,

      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  294,  293,  292,  291,  290,  289,  288,

      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  114,  189,  188,  187,  186,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  169,  168,
      165,  162,  161,  157,  156,  155,  154,  153,  152,  147,
      140,  139,  138,  137,  136,  135,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      118,   48,  117,  116,  113,  112,  109,  108,  103,  107,
      106,  105,  104,  103,   48,   41,   98,   97,   96,   95,
       84,   83,   74,   73,   49,   48,   43,   41,  519,   40,
       40,    5,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519
    } ;

static yyconst flex_int16_t yy_chk[822] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   13,
       13,   14,   14,   18,   19,   18,   20,   26,   20,   20,
       34,   23,   18,   21,   19,   18,   26,   21,   22,   22,
       28,   21,   22,   34,   19,   23,   21,   21,   23,   22,
       27,   23,   40,   29,   28,   29,   27,   32,   33,   46,
       46,   32,   33,   59,   59,   62,   83,   94,   90,   92,

       91,   32,   33,   90,   91,   95,   83,   33,   33,  100,
       92,  101,  111,   95,  119,  117,   62,   94,  122,  111,
      165,  165,  119,  136,  263,   40,  189,  189,  379,  517,
      122,  111,  117,  514,  136,  513,  356,  512,  511,  263,
      189,  510,  326,  326,  379,  326,  326,  356,  509,  508,
      189,  507,  100,  189,  101,  326,  356,  506,  326,  326,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  521,
      521,  505,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  522,  522,
      504,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  523,  523,  523,  523,

      523,  503,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  500,  499,  498,  497,  496,  495,

      494,  493,  492,  491,  490,  489,  488,  487,  486,  485,
      484,  482,  480,  479,  478,  476,  475,  474,  473,  472,
      471,  468,  467,  466,  465,  464,  463,  462,  461,  460,
      459,  456,  455,  453,  452,  451,  449,  448,  447,  446,
      445,  444,  442,  441,  440,  439,  437,  436,  435,  434,
      433,  432,  431,  430,  429,  428,  427,  426,  425,  423,
      422,  420,  418,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  386,  385,  384,
      383,  382,  381,  380,  378,  376,  375,  374,  373,  372,

      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  357,  355,  354,  353,  352,  351,  350,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      336,  335,  334,  333,  332,  330,  329,  328,  327,  325,
      324,  323,  322,  321,  319,  318,  317,  316,  314,  312,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  294,  293,  292,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  262,  261,  260,  258,  255,  254,  253,

      251,  250,  249,  247,  244,  243,  242,  241,  240,  239,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  227,
      226,  225,  224,  222,  221,  220,  219,  218,  217,  216,
      215,  213,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  195,  193,  191,  190,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  164,  163,  162,  159,  158,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  135,  134,  133,  132,

      130,  129,  128,  127,  126,  125,  124,  123,  121,  120,
      118,  113,  112,  110,  108,  107,  106,  105,   96,   93,
       89,   88,   87,   86,   85,   84,   81,   80,   79,   78,
       77,   76,   74,   73,   72,   71,   70,   69,   68,   67,
       66,   65,   64,   63,   61,   60,   58,   57,   55,   54,
       53,   52,   51,   50,   49,   41,   38,   37,   36,   35,
       31,   30,   25,   24,   17,   16,   11,    7,    5,    4,
        3,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int dfg__flex_debug;
int dfg__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *dfg_text;
#line 1 "dfgscanner.l"
/**************************************************************/
/* ********************************************************** */
/* *                                                        * */
/* *                 SCANNER FOR DFG SYNTAX                 * */
/* *                                                        * */
/* *  $Module:   DFG                                        * */ 
/* *                                                        * */
/* *  Copyright (C) 1997, 1998, 1999, 2000, 2001            * */
/* *  MPI fuer Informatik                                   * */
/* *                                                        * */
/* *  This program is free software; you can redistribute   * */
/* *  it and/or modify it under the terms of the GNU        * */
/* *  General Public License as published by the Free       * */
/* *  Software Foundation; either version 2 of the License, * */
/* *  or (at your option) any later version.                * */
/* *                                                        * */
/* *  This program is distributed in the hope that it will  * */
/* *  be useful, but WITHOUT ANY WARRANTY; without even     * */
/* *  the implied warranty of MERCHANTABILITY or FITNESS    * */
/* *  FOR A PARTICULAR PURPOSE.  See the GNU General Public * */
/* *  License for more details.                             * */
/* *                                                        * */
/* *  You should have received a copy of the GNU General    * */
/* *  Public License along with this program; if not, write * */
/* *  to the Free Software Foundation, Inc., 59 Temple      * */
/* *  Place, Suite 330, Boston, MA  02111-1307  USA         * */
/* *                                                        * */
/* *                                                        * */
/* $Revision: 1.4 $                                        * */
/* $State: Exp $                                            * */
/* $Date: 2007/02/23 14:36:49 $                             * */
/* $Author: weidenb $                                       * */
/* *                                                        * */
/* *             Contact:                                   * */
/* *             Christoph Weidenbach                       * */
/* *             MPI fuer Informatik                        * */
/* *             Stuhlsatzenhausweg 85                      * */
/* *             66123 Saarbruecken                         * */
/* *             Email: spass@mpi-inf.mpg.de                * */
/* *             Germany                                    * */
/* *                                                        * */
/* ********************************************************** */
/**************************************************************/
/* $RCSfile: dfgscanner.l,v $ */
#line 49 "dfgscanner.l"

#include <ctype.h>    /* for isprint */
#include <errno.h>
#include "misc.h"
#include "memory.h"
#include "symbol.h"
#include "term.h"
#include "dfg.h"
#include "dfgparser.h"

/* defined in dfgparser.y */
extern NAT  dfg_LINENUMBER;
extern BOOL dfg_IGNORETEXT;

static NAT dfg_CountNewlines(char*);

static __inline__ char* dfg_StringCopy(void)
{
  char *copy;
  copy = (char*) memory_Malloc(dfg_leng+1);
  strcpy(copy, dfg_text);
  return copy;
}

/* Force the scanner to read the input character by character */
/* Omit unused function yyunput */
/* Start conditions */

#line 866 "dfgscanner.c"

#define INITIAL 0
#define TXT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int dfg_wrap (void );
#else
extern int dfg_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( dfg_text, dfg_leng, 1, dfg_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( dfg_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( dfg_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, dfg_in))==0 && ferror(dfg_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(dfg_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int dfg_lex (void);

#define YY_DECL int dfg_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after dfg_text and dfg_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 84 "dfgscanner.l"


#line 1019 "dfgscanner.c"

	if ( (yy_init) )
		{
		(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! dfg_in )
			dfg_in = stdin;

		if ( ! dfg_out )
			dfg_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			dfg_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				dfg__create_buffer(dfg_in,YY_BUF_SIZE );
		}

		dfg__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of dfg_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 772 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 86 "dfgscanner.l"
return DFG_END_OF_CONSTRAINT_LITERALS;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 87 "dfgscanner.l"
return DFG_END_OF_ANTECEDENT_LITERALS;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 88 "dfgscanner.l"
return DFG_LITERAL_IS_SELECTED;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 "dfgscanner.l"
return DFG_AND;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 90 "dfgscanner.l"
return DFG_AUTHOR;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 91 "dfgscanner.l"
return DFG_AXIOMS;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 92 "dfgscanner.l"
return DFG_BEGPROB;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 93 "dfgscanner.l"
return DFG_BY;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "dfgscanner.l"
return DFG_BOX;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "dfgscanner.l"
return DFG_CLAUSE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "dfgscanner.l"
return DFG_CNF;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "dfgscanner.l"
return DFG_COMP;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "dfgscanner.l"
return DFG_CONJECS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "dfgscanner.l"
return DFG_CONV;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "dfgscanner.l"
return DFG_DATE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "dfgscanner.l"
return DFG_DESC;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "dfgscanner.l"
return DFG_DIA;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "dfgscanner.l"
return DFG_DIVERSITY;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "dfgscanner.l"
return DFG_DNF;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "dfgscanner.l"
return DFG_DOMAIN;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "dfgscanner.l"
return DFG_DOMRESTR;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "dfgscanner.l"
return DFG_EML;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 108 "dfgscanner.l"
return DFG_ENDLIST;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 109 "dfgscanner.l"
return DFG_ENDPROB;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 110 "dfgscanner.l"
return DFG_EQUAL;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 111 "dfgscanner.l"
return DFG_EQUIV;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 112 "dfgscanner.l"
return DFG_EXISTS;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 113 "dfgscanner.l"
return DFG_FALSE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 114 "dfgscanner.l"
return DFG_FORALL;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 115 "dfgscanner.l"
return DFG_FORMULA;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 116 "dfgscanner.l"
return DFG_FREELY;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 117 "dfgscanner.l"
return DFG_FUNC;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 118 "dfgscanner.l"
return DFG_GENERATED;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 119 "dfgscanner.l"
return DFG_HYPOTH;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 120 "dfgscanner.l"
return DFG_IDENTITY;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 121 "dfgscanner.l"
return DFG_IMPLIED;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 122 "dfgscanner.l"
return DFG_IMPLIES;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 123 "dfgscanner.l"
return DFG_CLSLIST;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 124 "dfgscanner.l"
return DFG_DECLLIST;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 125 "dfgscanner.l"
return DFG_DESCLIST;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 126 "dfgscanner.l"
return DFG_FORMLIST;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 127 "dfgscanner.l"
return DFG_GENSET;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 128 "dfgscanner.l"
return DFG_PRFLIST;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 129 "dfgscanner.l"
return DFG_SETTINGS;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 130 "dfgscanner.l"
return DFG_SPECIALFORMLIST;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 131 "dfgscanner.l"
return DFG_SYMLIST;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 132 "dfgscanner.l"
return DFG_TERMLIST;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 133 "dfgscanner.l"
return DFG_LOGIC;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 134 "dfgscanner.l"
return DFG_NAME;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 135 "dfgscanner.l"
return DFG_NOT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 136 "dfgscanner.l"
return DFG_OPERAT;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 137 "dfgscanner.l"
return DFG_OR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 138 "dfgscanner.l"
return DFG_PROP_FORMULA;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 139 "dfgscanner.l"
return DFG_PRED;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 140 "dfgscanner.l"
return DFG_PRDICAT;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 141 "dfgscanner.l"
return DFG_QUANTIF;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 142 "dfgscanner.l"
return DFG_RANRESTR;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 143 "dfgscanner.l"
return DFG_RANGE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 144 "dfgscanner.l"
return DFG_REL_FORMULA;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 145 "dfgscanner.l"
return DFG_SATIS;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 146 "dfgscanner.l"
return DFG_DOMPRED;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 147 "dfgscanner.l"
return DFG_SETFLAG;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 148 "dfgscanner.l"
return DFG_PREC;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 149 "dfgscanner.l"
return DFG_CLFORE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 150 "dfgscanner.l"
return DFG_SELECT;                   
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 151 "dfgscanner.l"
return DFG_SORT;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 152 "dfgscanner.l"
return DFG_SORTS;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 153 "dfgscanner.l"
return DFG_STATUS;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 154 "dfgscanner.l"
return DFG_STEP;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 155 "dfgscanner.l"
return DFG_SUBSORT;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 156 "dfgscanner.l"
return DFG_SUM;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 157 "dfgscanner.l"
return DFG_TEST;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 158 "dfgscanner.l"
return DFG_TRANSLPAIRS;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 159 "dfgscanner.l"
return DFG_TRUE;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 160 "dfgscanner.l"
return DFG_UNKNOWN;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 161 "dfgscanner.l"
return DFG_UNSATIS;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 162 "dfgscanner.l"
return DFG_VERSION;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 163 "dfgscanner.l"
return DFG_MINUS1;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 165 "dfgscanner.l"
/* one-line comment */
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 166 "dfgscanner.l"
{ /* Start of multiline comment */
				  if (dfg_IGNORETEXT) {
				    BEGIN(TXT);
				    yymore();
				  } else
				    return DFG_OPENBRACE;
				}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 173 "dfgscanner.l"
return DFG_CLOSEBRACE;
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 174 "dfgscanner.l"
yymore();
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 175 "dfgscanner.l"
yymore();
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 176 "dfgscanner.l"
{ BEGIN(INITIAL);
				  dfg_lval.string = dfg_StringCopy();
				  dfg_LINENUMBER += dfg_CountNewlines(dfg_text);
				  return DFG_TEXT;
				}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 181 "dfgscanner.l"
{ unsigned long n;
                                  errno = 0;
                                  n = strtoul(dfg_text, NULL, 10);
				  if (errno != 0 || n > INT_MAX) {
                                    misc_StartUserErrorReport();
                                    misc_UserErrorReport("\n Number too big in line %d.\n",
							 dfg_LINENUMBER);
                                    misc_FinishUserErrorReport();
                                  }
                                  dfg_lval.number = (int) n;
                                  return DFG_NUM;
                                }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 193 "dfgscanner.l"
{ dfg_lval.string = dfg_StringCopy();
                                  return DFG_ID;
                                }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 196 "dfgscanner.l"
/* ignore */
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 197 "dfgscanner.l"
dfg_LINENUMBER++;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 198 "dfgscanner.l"
return dfg_text[0];
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 199 "dfgscanner.l"
{ misc_StartUserErrorReport();
                                  misc_UserErrorReport("\n Illegal character '");
				  if (isprint((int)dfg_text[0]))
				    misc_UserErrorReport("%c",dfg_text[0]);
				  else
				    misc_UserErrorReport("\\x%x", (unsigned int) dfg_text[0]);
				  misc_UserErrorReport("' in line %d.\n", dfg_LINENUMBER);
                                  misc_FinishUserErrorReport();
                                }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 209 "dfgscanner.l"
ECHO;
	YY_BREAK
#line 1595 "dfgscanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TXT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed dfg_in at a new source and called
			 * dfg_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = dfg_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( dfg_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * dfg_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of dfg_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					dfg_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			dfg_restart(dfg_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 519);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					dfg_restart(dfg_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( dfg_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve dfg_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void dfg_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        dfg_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            dfg__create_buffer(dfg_in,YY_BUF_SIZE );
	}

	dfg__init_buffer(YY_CURRENT_BUFFER,input_file );
	dfg__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void dfg__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	dfg_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	dfg__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (dfg_wrap()) processing, but the only time this flag
	 * is looked at is after dfg_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void dfg__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	dfg_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE dfg__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) dfg_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dfg__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) dfg_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in dfg__create_buffer()" );

	b->yy_is_our_buffer = 1;

	dfg__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with dfg__create_buffer()
 * 
 */
    void dfg__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		dfg_free((void *) b->yy_ch_buf  );

	dfg_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a dfg_restart() or at EOF.
 */
    static void dfg__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	dfg__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then dfg__init_buffer was _probably_
     * called from dfg_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 1;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void dfg__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		dfg__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void dfg_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	dfg_ensure_buffer_stack();

	/* This block is copied from dfg__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from dfg__switch_to_buffer. */
	dfg__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void dfg_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	dfg__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		dfg__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void dfg_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)dfg_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)dfg_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE dfg__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) dfg_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dfg__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	dfg__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to dfg_lex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       dfg__scan_bytes() instead.
 */
YY_BUFFER_STATE dfg__scan_string (yyconst char * yy_str )
{
    
	return dfg__scan_bytes(yy_str,strlen(yy_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to dfg_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE dfg__scan_bytes  (yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) dfg_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in dfg__scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = dfg__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in dfg__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up dfg_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		dfg_text[dfg_leng] = (yy_hold_char); \
		(yy_c_buf_p) = dfg_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		dfg_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int dfg_get_lineno  (void)
{
        
    return dfg_lineno;
}

/** Get the input stream.
 * 
 */
FILE *dfg_get_in  (void)
{
        return dfg_in;
}

/** Get the output stream.
 * 
 */
FILE *dfg_get_out  (void)
{
        return dfg_out;
}

/** Get the length of the current token.
 * 
 */
int dfg_get_leng  (void)
{
        return dfg_leng;
}

/** Get the current token.
 * 
 */

char *dfg_get_text  (void)
{
        return dfg_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void dfg_set_lineno (int  line_number )
{
    
    dfg_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see dfg__switch_to_buffer
 */
void dfg_set_in (FILE *  in_str )
{
        dfg_in = in_str ;
}

void dfg_set_out (FILE *  out_str )
{
        dfg_out = out_str ;
}

int dfg_get_debug  (void)
{
        return dfg__flex_debug;
}

void dfg_set_debug (int  bdebug )
{
        dfg__flex_debug = bdebug ;
}

/* dfg_lex_destroy is for both reentrant and non-reentrant scanners. */
int dfg_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		dfg__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		dfg_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	dfg_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *dfg_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *dfg_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void dfg_free (void * ptr )
{
	free( (char *) ptr );	/* see dfg_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#undef YY_NEW_FILE
#undef YY_FLUSH_BUFFER
#undef yy_set_bol
#undef yy_new_buffer
#undef yy_set_interactive
#undef yytext_ptr
#undef YY_DO_BEFORE_ACTION

#ifdef YY_DECL_IS_OURS
#undef YY_DECL_IS_OURS
#undef YY_DECL
#endif
#line 209 "dfgscanner.l"



static NAT dfg_CountNewlines(char* Text)
{
  NAT result = 0;
  
  while (*Text != 0) {
    if (*Text++ == '\n')
      result++;
  }
  return result;
}

